services:
  postgres:
    image: postgres:16-alpine
    container_name: project1-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:

